version: "3"
networks:
  homeautomation:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  backend:
    build:
      context: ./backend
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    image: homeauto-back:latest
    networks:
      - homeautomation
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TEST_DB_NAME=${TEST_DB_NAME}
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    build: ./frontend
    image: homeauto-front:latest
    networks:
      - homeautomation
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_PROXY_PORT=${PORT}
      - VITE_PROXY_HOST=${VITE_PROXY_HOST}
  mariadb:
    image: mariadb:latest
    networks:
      - homeautomation
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
